yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [

    path('author/',
         views.AboutAuthorView.as_view(),
         name='author'
         ),
    # Статичная страница - Информация об авторе

    path('tech/',
         views.AboutTechView.as_view(),
         name='tech'
         ),
    # Статичная страница - Информация о примененных технологиях
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index,
         name='index'
         ),
    # Страница группы
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'
         ),
    # Профайл пользователя
    path('profile/<str:username>/',
         views.profile,
         name='profile'
         ),
    # Просмотр записи
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'
         ),
    # Изменение записи
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='update_post'
         ),
    # Создание записи
    path('create/',
         views.post_create,
         name='post_create'
         ),
    # Создание комментария
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
    # Виджет подписок
    path('follow/',
         views.follow_index,
         name='follow_index'
         ),
    # Создание подписки на автора
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    # Прекращение подписки на автора
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'


urlpatterns = [
    path('login/', LoginView.as_view(
         template_name='users/login.html'
         ),
         name='login'
         ),
    #  Авторизация
    path('logout/', LogoutView.as_view(
         template_name='users/logged_out.html'
         ),
         name='logout'
         ),
    #  Выход
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'
         ),
         name='password_change'
         ),
    #  Смена пароля
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    #  Сообщение об успешном изменении пароля
    path('signup/', views.SignUp.as_view(),
         name='signup'
         ),
    #  Регистрация
    path('password_reset/', PasswordResetView.as_view(
         template_name='users/password_reset_form.html'
         ),
         name='password_reset'
         ),
    #  Восстановление пароля, форма
    path('password_reset/done/', PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'
         ),
    #  Восстановление пароля, уведомление об отправке письма
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
         template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'
         ),
    #  Восстановление пароля, страница подтверждения сброса пароля
    path('reset/done/', PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
    #  Восстановление пароля, уведомление об успешной смене пароля
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

# Надстройка для отображения картинок
if settings.DEBUG:

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
<p>
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>  
</p>

yatube/templates/includes/header.html
{% load static %}
{% comment %} Сокращаем обращение к представлению {% endcomment %}
{% with request.resolver_match.view_name as view_name %} 
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link 
            {% if view_name  == 'about:author' %}
              active
            {% endif %}"
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
            {% if view_name  == 'about:tech' %}
              active
            {% endif %}"
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link
            {% if view_name  == 'posts:post_create' %}
              active
            {% endif %}"
          href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:password_change' %}
              active
            {% endif %}"
          href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.get_full_name }}
        <li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:login' %}
              active
            {% endif %}"
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:signup' %}
              active
            {% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>      
</header>
{% endwith %}