yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [

    path('author/',
         views.AboutAuthorView.as_view(),
         name='author'
         ),
    # Статичная страница - Информация об авторе

    path('tech/',
         views.AboutTechView.as_view(),
         name='tech'
         ),
    # Статичная страница - Информация о примененных технологиях
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index,
         name='index'
         ),
    # Страница группы
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'
         ),
    # Профайл пользователя
    path('profile/<str:username>/',
         views.profile,
         name='profile'
         ),
    # Просмотр записи
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'
         ),
    # Изменение записи
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='update_post'
         ),
    # Создание записи
    path('create/',
         views.post_create,
         name='post_create'
         ),
    # Создание комментария
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
    # Виджет подписок
    path('follow/',
         views.follow_index,
         name='follow_index'
         ),
    # Создание подписки на автора
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    # Прекращение подписки на автора
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

# Надстройка для отображения картинок
if settings.DEBUG:

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Post(CreatedModel):
    """Модель поста."""
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста',
                            )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор',
                               )
    group = models.ForeignKey('Group',
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              blank=True,
                              null=True,
                              verbose_name='Группа поста',
                              help_text='Группа, к которой'
                              'будет относиться пост',
                              )
    image = models.ImageField(verbose_name='Картинка',
                              upload_to='posts/',
                              blank=True,
                              help_text='Загрузите изображение',
                              )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Group(CreatedModel):
    """Модель группы."""
    title = models.CharField(max_length=200,
                             verbose_name='Название группы',
                             )
    slug = models.SlugField(max_length=255,
                            unique=True,
                            db_index=True
                            )
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title


class Comment(CreatedModel):
    """Модель комментария."""
    text = models.TextField(verbose_name='Текст комментария',
                            help_text='Введите текст комментария',
                            )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               verbose_name='Автор',
                               )
    post = models.ForeignKey('Post',
                             on_delete=models.CASCADE,
                             related_name='comments',
                             )


class Follow(models.Model):
    """Модель подписки на автора."""
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name="follower",
                             verbose_name='Подписчик',
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following',
                               verbose_name='Автор',
                               )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_user'),
        ]

yatube/posts/forms.py
from django import forms
from django.forms import Textarea

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """Форма для создания поста"""
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': Textarea(attrs={'cols': 40, 'rows': 10}),
        }

    def clean_subject(self):
        """Метод-валидатор для поля text."""
        data = self.cleaned_data['text']
        if '' in data():
            raise forms.ValidationError('А кто поле будет заполнять, Пушкин?')
        return data


class CommentForm(forms.ModelForm):
    """Форма для создания комментария"""
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def get_page_context(queryset, request):
    """Пагинация отдельной функцией."""
    paginator = Paginator(queryset, settings.DIVIDER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'page_obj': page_obj,
    }


def index(request):
    """Представление главной страницы."""
    template = 'posts/index.html'
    context = get_page_context(Post.objects.all(), request)
    return render(request, template, context)


def group_posts(request, slug):
    """Представление страницы группы."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    context = {
        'group': group,
        'post_list': post_list,
    }
    context.update(get_page_context(post_list, request))
    return render(request, template, context)


def post_detail(request, post_id):
    """Представление страницы отдельного поста."""
    template = 'posts/post_detail.html'
    singl_post = get_object_or_404(Post, id=post_id)
    user_profile = singl_post.author
    form = CommentForm()
    all_comments = singl_post.comments.all()
    count_posts = user_profile.posts.all().count()
    context = {
        'count_posts': count_posts,
        'singl_post': singl_post,
        'user_profile': user_profile,
        'form': form,
        'all_comments': all_comments,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """Представление страницы создания комментария."""
    # Получите пост
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post_id = post_id
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_edit(request, post_id):
    """Представление страницы редактирования поста."""
    template = 'posts/create_post.html'
    changing_post = get_object_or_404(Post, id=post_id)
    if changing_post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=changing_post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Представление страницы создания поста."""
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def follow_index(request):
    """Представление страницы создания поста."""
    template = 'posts/follow.html'
    context = get_page_context(
        Post.objects.filter(author__following__user=request.user), request
    )
    return render(request, template, context)


def profile(request, username):
    """Представление страницы профиля."""
    template = 'posts/profile.html'
    user_profile = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user_profile,
    ).exists()
    post_list = user_profile.posts.all()
    count_posts = post_list.count()
    context = {
        'user_profile': user_profile,
        'post_list': post_list,
        'count_posts': count_posts,
        'following': following,
    }
    context.update(get_page_context(post_list, request))
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""
    author = get_object_or_404(User, username=username)
    follower_user = request.user
    if author != follower_user:
        Follow.objects.get_or_create(user=follower_user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Дизлайк, отписка."""
    author = get_object_or_404(User, username=username)
    follower_user = request.user
    Follow.objects.filter(user=follower_user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% comment %} Подключили кастомные фильтры {% endcomment %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %} 
          </div>
          <div class="card-body">        
            <form method="post" action="" enctype="multipart/form-data">
              <input type="hidden" name="csrfmiddlewaretoken" value="">            
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger" >*</span>                  
                </label>
                {% csrf_token %}
                {{ form.text|add_classes:'form-control' }}
                <small id="id_text-help" class="form-text text-muted">
                  {% if is_edit %}
                    Отредактированный пост
                  {% else %}
                    {{ form.text.help_text }}
                  {% endif %}
                </small>

              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Картинка
                  <br>
                {{ form.image|add_classes:'form-control' }}
                <small id="id_image-help" class="form-text text-muted">
                  {{ form.image.help_text }}
                </small>
              </div>
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Group
                </label>
                  {{ form.group|add_classes:'form-control' }}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}               
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% comment %} {% now "Y-m-d H:i:s" %} {% endcomment %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}

  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <article>
      {% cache 20 follow_page page_obj.number %} 
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% endcache %} 
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ group.title }}{% endblock %}

{% block header %} {{ group.title }} {% endblock %}

{% block content %}
  <div class="container py-5">
    <h1> Записи сообщества: </h1>
    <p> {{ group.description }} </p>
    <p>
      Создана: {{ group.pub_date|date:"d E Y" }} <hr>
    </p>
    <article>
      {% for post in page_obj %}
       {% include 'posts/includes/post_list.html' %}
         {% if post.group %}
         <a href="{% url 'posts:group_list' post.group.slug %}">
           все записи группы
         </a>
       {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% comment %} {% now "Y-m-d H:i:s" %} {% endcomment %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}

  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <article>
      {% cache 20 index_page page_obj.number %} 
      {% for post in page_obj %}  
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% endcache %}
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>
 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
  {{ singl_post }}

{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
          <li class="list-group-item">
              Дата публикации: {{ singl_post.pub_date|date:"d E Y" }} 
          </li>
          {% if singl_post.group %}
            <li class="list-group-item">
              Группа: {{ singl_post.group.title }} <br>
            <a href="{% url 'posts:group_list' singl_post.group.slug %}">
              все записи группы
            </a>
          {% endif %}
              <li class="list-group-item">
              Автор: {{ singl_post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ count_posts }}</span>
          </li>
          <li class="list-group-item">
              <a href="{% url 'posts:profile' singl_post.author %}">
              все посты пользователя
              </a>
          </li>
          </ul>
      </aside>
      <article class="col-12 col-md-9">

        {% thumbnail singl_post.image "960x390" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}

          <p>
            {{ singl_post.text }}
          </p>
          {% if request.user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'posts:update_post' singl_post.id %}">
             редактировать запись
            </a>
          {% endif %}
      </article>

      {% if user.is_authenticated %}
        {% include 'posts/includes/comment_card.html' %} 
      {% endif %}
      {% include 'posts/includes/comment_feed.html' %}
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Профайл пользователя {{ user_profile.get_full_name }}
{% endblock %}

{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ user_profile.get_full_name }}</h1>
    <h3>Всего постов: {{ count_posts }}</h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' user_profile.username %}" role="button"
    >
      Отписаться
    </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' user_profile.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
    <article>
      {% for post in page_obj %}
        <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        </ul>
        <p>
          {% thumbnail post.image "960x390" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a> </br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
          <hr>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>
{% endblock %}